### ISSUE TITLE
Fehler "Call to undefined method DPCalendarHelper::fetchContent()"

### ISSUE THREAD

**Issue by BernhardK91** [hiorgserver/HiOrg-Joomla-Plugin#8]
Sobald das HiOrg-Plugin aktiviert ist, funktioniert DPCalendar nicht mehr. Die Methode "fetchContent()" ist nicht in _DPCalendarHelper_, sondern in _DPCalendarPlugin_:

https://github.com/Digital-Peak/DPCalendar-Free/blob/main/com_dpcalendar/admin/libraries/dpcalendar/DPCalendar/Plugin/DPCalendarPlugin.php

**Comment by chrisblech** [comment]
Closed by #9
